episodes: 1000000
seed: 42
out: mc_agent.pkl
agent_type: mc_first_visit
epsilon_params:
  epsilon_start: 0.2
  epsilon_min: 0.05
  epsilon_decay: 0.0001
evaluation:
  matches: 200
  target_points: 40
  seed: 123
  # output_dir: optional override; defaults to latest session dir
